# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build GoApp
      run: go build -o run
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Create Dockerfile
      run: |
        echo: "FROM ubuntu:latest" > Dockerfile
        echo: "WORKDIR /app" > Dockerfile
        
    - name : Show Dockerfile
      run: cat Dockerfile
      
    - name: Build Docker
      run: |
        docker build -t my_go_app .
