# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 # lint:
  #  runs-on: ubuntu-latest

 #   steps:
  #  - name: Checkout Repository
   #   uses: actions/checkout@v3

    #- name: Set up Go
     # uses: actions/setup-go@v4
      #with:
       # go-version: 1.21.6

    #- name: Install golangci-lint
     # run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    #- name: Run golangci-lint
     # run: golangci-lint run

  build:
    runs-on: ubuntu-latest
   # needs: lint
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build GoApp
      run: go build -o run
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Create Dockerfile
      run: |
        echo "FROM ubuntu:latest" >> Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY run /app/"
        echo "CMD [\"/bin/bash\"]" >> Dockerfile
        echo "CMD ["go", "test", "./..."]" >> Dockerfile
        
    - name : Show Dockerfile
      run: cat Dockerfile
            
    - name: Build Docker
      run: |
        docker build -t hivemind:latest .
    - name: Docker Run
      run: docker run hivemind:latest 
  test:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - uses: actions/checkout@v4#
    
    - name: Docker Run
      run: docker run hivemind:latest 

