name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate SSL certificate
      run: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ssl.key -out ssl.crt -subj "/CN=mydomain.com/O=My Company Name/C=US"

    - name: Create Assets directory
      run: mkdir -p Assets

    - name: Copy SSL certificate to Assets directory
      run: cp ssl.crt ssl.key Assets/

    - name: Build Go program
      run: go build -o myapp .

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker image
      run: docker tag myapp ghcr.io/${{ github.repository_owner }}/myapp:latest

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/myapp:latest

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          This is the first release.
        draft: false
        prerelease: false
        files: |
          Assets/*
